hello_world:
    path: /hello_world
    controller: UserEx\Todo\Controllers\HelloWorldController
    action: indexAction
    method: GET

todo:
    path: /
    controller: UserEx\Todo\Controllers\TodoController
    action: indexAction
    method: GET

todo_add:
    path: /ajax/add
    controller: UserEx\Todo\Controllers\TodoController
    action: addAction
    method: POST
    expose: true
    
todo_delete:
    path: /ajax/delete
    controller: UserEx\Todo\Controllers\TodoController
    action: deleteAction
    method: POST
    expose: true
    
todo_load_list:
    path: /ajax/load_list
    controller: UserEx\Todo\Controllers\TodoController
    action: getListAction
    method: POST
    expose: true

todo_toggle:
    path: /ajax/toggle
    controller: UserEx\Todo\Controllers\TodoController
    action: toggleAction
    method: POST
    expose: true
    
todo_toggle_all:
    path: /ajax/toggle_all
    controller: UserEx\Todo\Controllers\TodoController
    action: toggleAllTodoAction
    method: POST
    expose: true

todo_delete_completed:
    path: /ajax/delete_completed
    controller: UserEx\Todo\Controllers\TodoController
    action: deleteCompletedAction
    method: POST
    expose: true
        
registration:
    path: /registration
    controller: UserEx\Todo\Controllers\UserRegistrationController
    action: indexAction
    method: GET
    
sign_up:
    path: /sign_up
    controller: UserEx\Todo\Controllers\UserRegistrationController
    action: signUpAction
    method: POST
    
login:
    path: /login
    controller: UserEx\Todo\Controllers\LoginController
    action: indexAction
    method: GET
    
sign_in:
    path: /sign_in
    controller: UserEx\Todo\Controllers\LoginController
    action: signInAction
    method: POST
    
logout:
    path: /logout
    controller: UserEx\Todo\Controllers\LoginController
    action: logoutAction
    method: GET